### ISSUE TITLE
split: output file suffixes exhausted

### ISSUE THREAD

**Issue by tomas-pluskal** [transXpress/transXpress#12]
This error happens at this step when there are >10000 trinity commands:
```
split --numeric-suffixes=1 -l 100 {input} {output}/job_ &>> {log}
```
Seems like there is no easy way to make split produce unlimited number of files... :(

**Comment by photocyte** [comment]
Interesting, presumably a design choice? Perhaps worrying about file system limitations.

**Comment by tomas-pluskal** [comment]
I guess we can just use ```split -a 6``` - if there are more than 100000000 Trinity commands, it will take years to finish, anyway, so nobody will notice the error.

**Comment by tomas-pluskal** [comment]
Correction - it is possible for split to produce arbitrary number of files!
```
$ split --numeric-suffixes=1 -l 1 file
split: output file suffixes exhausted

$ split -d -l 1 file
```
The second command works fine with no error. And this is not documented in the man page!

**Comment by SimZhou** [comment]
> Correction - it is possible for split to produce arbitrary number of files!
> 
> ```
> $ split --numeric-suffixes=1 -l 1 file
> split: output file suffixes exhausted
> 
> $ split -d -l 1 file
> ```
> 
> The second command works fine with no error. And this is not documented in the man page!

There's a problem with second command:
when trying to split into files more than 90, the numeric suffix gives incorrect result:
```
> split -l 888329 -d text_enum_raw
```
The line above gives me:
![image](https://user-images.githubusercontent.com/11748629/190884056-df4f8aa8-0912-4755-a1c8-7b43d0d289e8.png)

**Comment by CalounovaT** [comment]
@SimZhou Yes, you are right.
This seems to be the design of split command so that names are automatically sorted numerically and not lexicographically.
See this: https://unix.stackexchange.com/a/396130

It should not have any effect on functionality of transXpress to my knowledge.
We use this command for example in rule trimmomatic_split where file with following name would be generated: `trimmomatic/sample_9001`
and since in following rules are matching files based on this pattern: `trimmomatic/sample_{job_index}`, it should not make a difference if a file is called  `trimmomatic/sample_9001` or `trimmomatic/sample_91`.
